package de.fhdw.ify208.ticketmaster.webapp.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "customerservice", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Customerservice {


    /**
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.AddressListDTO
     */
    @WebMethod(operationName = "GetCustomerAddresses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCustomerAddresses", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerAddresses")
    @ResponseWrapper(localName = "GetCustomerAddressesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerAddressesResponse")
    public AddressListDTO getCustomerAddresses(
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer);

    /**
     * @param userName
     * @param password
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.CustomerDTO
     */
    @WebMethod(operationName = "SignOn")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SignOn", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.SignOn")
    @ResponseWrapper(localName = "SignOnResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.SignOnResponse")
    public CustomerDTO signOn(
            @WebParam(name = "userName", targetNamespace = "")
            String userName,
            @WebParam(name = "password", targetNamespace = "")
            String password);

    /**
     * @param newPassword
     * @param userName
     * @param oldPassword
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "ChangeCustomer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChangeCustomer", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.ChangeCustomer")
    @ResponseWrapper(localName = "ChangeCustomerResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.ChangeCustomerResponse")
    public BaseDTO changeCustomer(
            @WebParam(name = "userName", targetNamespace = "")
            String userName,
            @WebParam(name = "oldPassword", targetNamespace = "")
            String oldPassword,
            @WebParam(name = "newPassword", targetNamespace = "")
            String newPassword);

    /**
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.CustomerDTO
     */
    @WebMethod(operationName = "RegisterCustomer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterCustomer", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterCustomer")
    @ResponseWrapper(localName = "RegisterCustomerResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterCustomerResponse")
    public CustomerDTO registerCustomer(
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer);

    /**
     * @param address
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.AddressDTO
     */
    @WebMethod(operationName = "MaintainAddress")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MaintainAddress", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.MaintainAddress")
    @ResponseWrapper(localName = "MaintainAddressResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.MaintainAddressResponse")
    public AddressDTO maintainAddress(
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer,
            @WebParam(name = "address", targetNamespace = "")
            AddressDTO address);

    /**
     * @param address
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "RemoveAddress")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveAddress", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RemoveAddress")
    @ResponseWrapper(localName = "RemoveAddressResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RemoveAddressResponse")
    public BaseDTO removeAddress(
            @WebParam(name = "customer", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            CustomerDTO customer,
            @WebParam(name = "address", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            AddressDTO address);

    /**
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "CloseCustomerProfile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CloseCustomerProfile", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CloseCustomerProfile")
    @ResponseWrapper(localName = "CloseCustomerProfileResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CloseCustomerProfileResponse")
    public BaseDTO closeCustomerProfile(
            @WebParam(name = "customer", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            CustomerDTO customer);

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetCustomerTypes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCustomerTypes", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerTypes")
    @ResponseWrapper(localName = "GetCustomerTypesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerTypesResponse")
    public TypeCodeListDTO getCustomerTypes();

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetAddressTypes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAddressTypes", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetAddressTypes")
    @ResponseWrapper(localName = "GetAddressTypesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetAddressTypesResponse")
    public TypeCodeListDTO getAddressTypes();

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.CountryListDTO
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCountriesResponse")
    public CountryListDTO getCountries();

}
