package de.fhdw.ify208.ticketmaster.webapp.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "eventservice", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Eventservice {


    /**
     * @param artistName
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.EventListDTO
     */
    @WebMethod(operationName = "GetEventsByArtists")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventsByArtists", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByArtists")
    @ResponseWrapper(localName = "GetEventsByArtistsResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByArtistsResponse")
    public EventListDTO getEventsByArtists(
            @WebParam(name = "artistName", targetNamespace = "")
            String artistName);

    /**
     * @param cityName
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.EventListDTO
     */
    @WebMethod(operationName = "GetEventsByLocation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventsByLocation", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByLocation")
    @ResponseWrapper(localName = "GetEventsByLocationResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByLocationResponse")
    public EventListDTO getEventsByLocation(
            @WebParam(name = "cityName", targetNamespace = "")
            String cityName);

    /**
     * @param genre
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.EventListDTO
     */
    @WebMethod(operationName = "GetEventsByGenre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventsByGenre", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByGenre")
    @ResponseWrapper(localName = "GetEventsByGenreResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByGenreResponse")
    public EventListDTO getEventsByGenre(
            @WebParam(name = "genre", targetNamespace = "")
            String genre);

    /**
     * @param category
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.EventListDTO
     */
    @WebMethod(operationName = "GetEventsByCategory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventsByCategory", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByCategory")
    @ResponseWrapper(localName = "GetEventsByCategoryResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByCategoryResponse")
    public EventListDTO getEventsByCategory(
            @WebParam(name = "category", targetNamespace = "")
            String category);

    /**
     * @param startDate
     * @param endDate
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.EventListDTO
     */
    @WebMethod(operationName = "GetEventsByDateRange")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventsByDateRange", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByDateRange")
    @ResponseWrapper(localName = "GetEventsByDateRangeResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventsByDateRangeResponse")
    public EventListDTO getEventsByDateRange(
            @WebParam(name = "startDate", targetNamespace = "")
            XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "")
            XMLGregorianCalendar endDate);

    /**
     * @param event
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "RegisterNewEvent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterNewEvent", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterNewEvent")
    @ResponseWrapper(localName = "RegisterNewEventResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterNewEventResponse")
    public BaseDTO registerNewEvent(
            @WebParam(name = "event", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            EventDTO event);

    /**
     * @param artist
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "RegisterNewArtist")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterNewArtist", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterNewArtist")
    @ResponseWrapper(localName = "RegisterNewArtistResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RegisterNewArtistResponse")
    public BaseDTO registerNewArtist(
            @WebParam(name = "artist", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            ArtistDTO artist);

    /**
     * @param event
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "CancelEvent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelEvent", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CancelEvent")
    @ResponseWrapper(localName = "CancelEventResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CancelEventResponse")
    public BaseDTO cancelEvent(
            @WebParam(name = "event", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
            EventDTO event);

    /**
     * @param event
     * @param rating
     * @param comment
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "RateEvent")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RateEvent", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RateEvent")
    @ResponseWrapper(localName = "RateEventResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.RateEventResponse")
    public BaseDTO rateEvent(
            @WebParam(name = "event", targetNamespace = "")
            EventDTO event,
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer,
            @WebParam(name = "rating", targetNamespace = "")
            double rating,
            @WebParam(name = "comment", targetNamespace = "")
            String comment);

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetGenres")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetGenres", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetGenres")
    @ResponseWrapper(localName = "GetGenresResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetGenresResponse")
    public TypeCodeListDTO getGenres();

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetCategories")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCategoriesResponse")
    public TypeCodeListDTO getCategories();

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetEventStatuses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEventStatuses", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventStatuses")
    @ResponseWrapper(localName = "GetEventStatusesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetEventStatusesResponse")
    public TypeCodeListDTO getEventStatuses();

    /**
     * @param filter
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.ArtistListDTO
     */
    @WebMethod(operationName = "FindArtists")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindArtists", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.FindArtists")
    @ResponseWrapper(localName = "FindArtistsResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.FindArtistsResponse")
    public ArtistListDTO findArtists(
            @WebParam(name = "filter", targetNamespace = "")
            String filter);

    /**
     * @param filter
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.AddressListDTO
     */
    @WebMethod(operationName = "FindLocations")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindLocations", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.FindLocations")
    @ResponseWrapper(localName = "FindLocationsResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.FindLocationsResponse")
    public AddressListDTO findLocations(
            @WebParam(name = "filter", targetNamespace = "")
            String filter);

}
