package de.fhdw.ify208.ticketmaster.webapp.webservices;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "EventServiceImplService", targetNamespace = "http://service.ticketmaster.ify208.fhdw.de/", wsdlLocation = "http://localhost:8080/eventservice?wsdl")
public class EventServiceImplService
        extends Service {

    private final static URL EVENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.fhdw.ify208.ticketmaster.webapp.webservices.EventServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.fhdw.ify208.ticketmaster.webapp.webservices.EventServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/eventservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/eventservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EVENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EventServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventServiceImplService() {
        super(EVENTSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.ticketmaster.ify208.fhdw.de/", "EventServiceImplService"));
    }

    /**
     * @return returns Eventservice
     */
    @WebEndpoint(name = "EventServiceImplPort")
    public Eventservice getEventServiceImplPort() {
        return super.getPort(new QName("http://service.ticketmaster.ify208.fhdw.de/", "EventServiceImplPort"), Eventservice.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns Eventservice
     */
    @WebEndpoint(name = "EventServiceImplPort")
    public Eventservice getEventServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ticketmaster.ify208.fhdw.de/", "EventServiceImplPort"), Eventservice.class, features);
    }

}
