package de.fhdw.ify208.ticketmaster.webapp.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "orderservice", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Orderservice {


    /**
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.OrderListDTO
     */
    @WebMethod(operationName = "GetCustomerOrders")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCustomerOrders", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerOrders")
    @ResponseWrapper(localName = "GetCustomerOrdersResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetCustomerOrdersResponse")
    public OrderListDTO getCustomerOrders(
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer);

    /**
     * @param billingTo
     * @param event
     * @param shippingTo
     * @param quantity
     * @param customer
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.OrderDTO
     */
    @WebMethod(operationName = "PlaceOrder")
    @WebResult(name = "order", targetNamespace = "")
    @RequestWrapper(localName = "PlaceOrder", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.PlaceOrder")
    @ResponseWrapper(localName = "PlaceOrderResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.PlaceOrderResponse")
    public OrderDTO placeOrder(
            @WebParam(name = "event", targetNamespace = "")
            EventDTO event,
            @WebParam(name = "customer", targetNamespace = "")
            CustomerDTO customer,
            @WebParam(name = "shippingTo", targetNamespace = "")
            AddressDTO shippingTo,
            @WebParam(name = "billingTo", targetNamespace = "")
            AddressDTO billingTo,
            @WebParam(name = "quantity", targetNamespace = "")
            int quantity);

    /**
     * @param order
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.BaseDTO
     */
    @WebMethod(operationName = "CancelOrder")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.CancelOrderResponse")
    public BaseDTO cancelOrder(
            @WebParam(name = "order", targetNamespace = "")
            OrderDTO order);

    /**
     * @return returns de.fhdw.ify208.ticketmaster.webapp.webservices.TypeCodeListDTO
     */
    @WebMethod(operationName = "GetOrderStatuses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetOrderStatuses", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetOrderStatuses")
    @ResponseWrapper(localName = "GetOrderStatusesResponse", targetNamespace = "de.fhdw.ify208.ticketmaster.common.model", className = "de.fhdw.ify208.ticketmaster.webapp.webservices.GetOrderStatusesResponse")
    public TypeCodeListDTO getOrderStatuses();

}
